package org.mg.iap

enum class BillingResult {
    OK,
    USER_CANCELED,
    SERVICE_UNAVAILABLE,
    BILLING_UNAVAILABLE,
    ITEM_UNAVAILABLE,
    DEVELOPER_ERROR,
    ERROR,
    ITEM_ALREADY_OWNED,
    ITEM_NOT_OWNED,
    PROMO_ELIGIBLE,
    NOT_PROMO_ELIGIBLE,
    EXPIRED_OFFER_TOKEN
}